@startuml
'https://plantuml.com/component-diagram

package "Dto" {
  [CreateAccountDto]
  [AccountDetailsDto]
  [BalanceDto]
  [RequestTransactionDto]
  [TransactionDetailsDto]
}

package "Controller" {
  [AccountController] as account
  [BalanceController] as balance
  [TransactionController] as transaction
}

package "repository" {
  [AccountRepository] as accountRepo
  [BalanceRepository] as balanceRepo
  [TransactionRepository] as transactionRepo
}

package "Service" {
  [AccountService] as accountService
  [BalanceService] as balanceService
  [TransactionService] as transactionService
}

package "client interface" {
[exchangeRateClient] as exchangeRateInterface
}

database "Account DB" {
  folder "Account table" as accountTable {
    [Account 1 ..] as accountRecord
  }
  folder "Balance table" as balanceTable {
    [balance 1, ..] as balanceRecord
  }
  folder "Transaction table" as transactionTable {
    [transaction 1, 2, ..]
  }

  accountRecord ..> balanceRecord : 1-1 mapping
}

'account creation
Http --down-> account : create account
account -> accountService
accountService -> accountRepo
accountRepo -> accountTable

'balance addition
Http -down-> balance : create balance
balance --> balanceService
balanceService --> balanceRepo
balanceRepo --> balanceTable

'debit credit operation
Http -down-> transaction : perform debit-credit operation
transaction --> transactionService
transactionService --> exchangeRateInterface
exchangeRateInterface -> external_Http_call
transactionService --> transactionRepo
transactionRepo --> transactionTable

@enduml
